/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerEletron;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author unifaljesus
 */
public class Eletron extends javax.swing.JFrame {

    /**
     * Creates new form Eletron
     */
    public Eletron() {
        initComponents();
        ce = new ControllerEletron(this);
    }

    public JButton getBtEnviar() {
        return btEnviar;
    }

    public void setBtEnviar(JButton btEnviar) {
        this.btEnviar = btEnviar;
    }

    public JLabel getjLabel1() {
        return lblTitulo;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.lblTitulo = jLabel1;
    }

    public JLabel getLblA() {
        return lblA;
    }

    public void setLblA(JLabel lblA) {
        this.lblA = lblA;
    }

    public JLabel getLblB() {
        return lblB;
    }

    public void setLblB(JLabel lblB) {
        this.lblB = lblB;
    }

    public JLabel getLblDados() {
        return lblDados;
    }

    public void setLblDados(JLabel lblDados) {
        this.lblDados = lblDados;
    }

    public JLabel getLblLargura() {
        return lblLargura;
    }

    public void setLblLargura(JLabel lblLargura) {
        this.lblLargura = lblLargura;
    }

    public JLabel getLblNf() {
        return lblNf;
    }

    public void setLblNf(JLabel lblNf) {
        this.lblNf = lblNf;
    }

    public JLabel getLblNi() {
        return lblNi;
    }

    public void setLblNi(JLabel lblNi) {
        this.lblNi = lblNi;
    }

    public JLabel getLblUnidade() {
        return lblUnidade;
    }

    public void setLblUnidade(JLabel lblUnidade) {
        this.lblUnidade = lblUnidade;
    }

    public JLabel getLblUnidade1() {
        return lblUnidade1;
    }

    public void setLblUnidade1(JLabel lblUnidade1) {
        this.lblUnidade1 = lblUnidade1;
    }

    public JLabel getLblUnidade2() {
        return lblUnidade2;
    }

    public void setLblUnidade2(JLabel lblUnidade2) {
        this.lblUnidade2 = lblUnidade2;
    }

    public JTextField getTxtAe() {
        return txtAe;
    }

    public void setTxtAe(JTextField txtAe) {
        this.txtAe = txtAe;
    }

    public JTextField getTxtBe() {
        return txtBe;
    }

    public void setTxtBe(JTextField txtBe) {
        this.txtBe = txtBe;
    }

    public JTextField getTxtLargurae() {
        return txtLargurae;
    }

    public void setTxtLargurae(JTextField txtLargurae) {
        this.txtLargurae = txtLargurae;
    }

    public JTextField getTxtNfe() {
        return txtNfe;
    }

    public void setTxtNfe(JTextField txtNfe) {
        this.txtNfe = txtNfe;
    }

    public JTextField getTxtNie() {
        return txtNie;
    }

    public void setTxtNie(JTextField txtNie) {
        this.txtNie = txtNie;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JPanel getPanelEletron() {
        return panelEletron;
    }

    public void setPanelEletron(JPanel panelEletron) {
        this.panelEletron = panelEletron;
    }

    public JTextArea getTxtEletron() {
        return txtEletron;
    }

    public void setTxtEletron(JTextArea txtEletron) {
        this.txtEletron = txtEletron;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEletron = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEletron = new javax.swing.JTextArea();
        btEnviar = new javax.swing.JButton();
        txtLargurae = new javax.swing.JTextField();
        txtNie = new javax.swing.JTextField();
        txtNfe = new javax.swing.JTextField();
        lblDados = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblNf = new javax.swing.JLabel();
        lblLargura = new javax.swing.JLabel();
        lblUnidade2 = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblNi = new javax.swing.JLabel();
        txtAe = new javax.swing.JTextField();
        lblUnidade1 = new javax.swing.JLabel();
        txtBe = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();
        lblResutados = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAIXA 1D");
        setPreferredSize(new java.awt.Dimension(800, 800));
        setSize(new java.awt.Dimension(800, 800));

        panelEletron.setBackground(new java.awt.Color(153, 204, 255));
        panelEletron.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelEletron.setPreferredSize(new java.awt.Dimension(800, 800));

        txtEletron.setColumns(20);
        txtEletron.setRows(5);
        jScrollPane1.setViewportView(txtEletron);

        btEnviar.setBackground(new java.awt.Color(153, 204, 255));
        btEnviar.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btEnviar.setText("Enviar");
        btEnviar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        lblDados.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblDados.setText("Dados para a probabilidade:");

        lblA.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblA.setText("a:");

        lblNf.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblNf.setText("N final da partícula (Nf):");

        lblLargura.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblLargura.setText("Largura da caixa (L):");

        lblUnidade2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblUnidade2.setText("m");

        lblB.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblB.setText("b:");

        lblNi.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblNi.setText("N inicial da partícula (Ni):");

        lblUnidade1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblUnidade1.setText("m");

        lblTitulo.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        lblTitulo.setText("Elétron");

        lblUnidade.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblUnidade.setText("m");

        lblResutados.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblResutados.setText("Resultados");

        javax.swing.GroupLayout panelEletronLayout = new javax.swing.GroupLayout(panelEletron);
        panelEletron.setLayout(panelEletronLayout);
        panelEletronLayout.setHorizontalGroup(
            panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEletronLayout.createSequentialGroup()
                .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEletronLayout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelEletronLayout.createSequentialGroup()
                                    .addComponent(lblNi)
                                    .addGap(33, 33, 33)
                                    .addComponent(txtNie, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelEletronLayout.createSequentialGroup()
                                    .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNf)
                                        .addComponent(lblLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDados))
                                    .addGap(20, 20, 20)
                                    .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTitulo)
                                        .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panelEletronLayout.createSequentialGroup()
                                                .addComponent(txtLargurae, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblUnidade))
                                            .addComponent(txtNfe, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelEletronLayout.createSequentialGroup()
                                                .addComponent(lblA)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtAe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblUnidade1)
                                                .addGap(35, 35, 35)
                                                .addComponent(lblB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtBe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblUnidade2)
                                                .addGap(33, 33, 33)))))))
                        .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelEletronLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEletronLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelEletronLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblResutados, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        panelEletronLayout.setVerticalGroup(
            panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEletronLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLargurae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNi)
                    .addComponent(txtNie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNf)
                    .addComponent(txtNfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEletronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDados)
                    .addComponent(lblA)
                    .addComponent(lblUnidade1)
                    .addComponent(txtAe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblB)
                    .addComponent(lblUnidade2)
                    .addComponent(txtBe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblResutados, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Menu");

        jMenuItem1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuItem1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("Página Inicial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(51, 153, 255));
        jMenuItem2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setText("Poço Potencial Unidimensional - Próton");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(51, 153, 255));
        jMenuItem3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setText("Função de Onda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEletron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEletron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        String resultados = ce.entradasTeclado();
        txtEletron.setText("\n" + resultados);
    }//GEN-LAST:event_btEnviarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PaginaInicial pag = new PaginaInicial();
        pag.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Proton pro = new Proton();
        pro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ParametrosCaixaParticula pcp = new ParametrosCaixaParticula();
        pcp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Eletron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Eletron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Eletron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Eletron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Eletron().setVisible(true);
//            }
//        });
//    }

    private ControllerEletron ce;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblDados;
    private javax.swing.JLabel lblLargura;
    private javax.swing.JLabel lblNf;
    private javax.swing.JLabel lblNi;
    private javax.swing.JLabel lblResutados;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JLabel lblUnidade1;
    private javax.swing.JLabel lblUnidade2;
    private javax.swing.JPanel panelEletron;
    private javax.swing.JTextField txtAe;
    private javax.swing.JTextField txtBe;
    private javax.swing.JTextArea txtEletron;
    private javax.swing.JTextField txtLargurae;
    private javax.swing.JTextField txtNfe;
    private javax.swing.JTextField txtNie;
    // End of variables declaration//GEN-END:variables
}
