/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerCaixaParticula;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Aline Rocha
 */
public class ParametrosCaixaParticula extends javax.swing.JFrame {

    /**
     * Creates new form ParametrosCaixaParticula
     */
    public ParametrosCaixaParticula() {
        initComponents();
        c = new ControllerCaixaParticula(this);
    }

    public JButton getBtEnviar() {
        return btEnviar;
    }

    public void setBtEnviar(JButton btEnviar) {
        this.btEnviar = btEnviar;
    }

    public JLabel getLblA() {
        return lblA;
    }

    public void setLblA(JLabel lblA) {
        this.lblA = lblA;
    }

    public JLabel getLblK() {
        return lblK;
    }

    public void setLblK(JLabel lblK) {
        this.lblK = lblK;
    }

    public JLabel getLblParametros() {
        return lblParametros;
    }

    public void setLblParametros(JLabel lblParametros) {
        this.lblParametros = lblParametros;
    }

    public JLabel getLblUnidadeA() {
        return lblUnidadeA;
    }

    public void setLblUnidadeA(JLabel lblUnidadeA) {
        this.lblUnidadeA = lblUnidadeA;
    }

    public JLabel getLblUnidadeK() {
        return lblUnidadeK;
    }

    public void setLblUnidadeK(JLabel lblUnidadeK) {
        this.lblUnidadeK = lblUnidadeK;
    }

    public JLabel getLblUnidadeXp() {
        return lblUnidadeXp;
    }

    public void setLblUnidadeXp(JLabel lblUnidadeXp) {
        this.lblUnidadeXp = lblUnidadeXp;
    }

    public JLabel getLblXp() {
        return lblXp;
    }

    public void setLblXp(JLabel lblXp) {
        this.lblXp = lblXp;
    }

    public JPanel getPanelParametros() {
        return panelParametros;
    }

    public void setPanelParametros(JPanel panelParametros) {
        this.panelParametros = panelParametros;
    }

    public JTextField getTxtA() {
        return txtA;
    }

    public void setTxtA(JTextField txtA) {
        this.txtA = txtA;
    }

    public JTextField getTxtK() {
        return txtK;
    }

    public void setTxtK(JTextField txtK) {
        this.txtK = txtK;
    }

    public JTextField getTxtXp() {
        return txtXp;
    }

    public void setTxtXp(JTextField txtXp) {
        this.txtXp = txtXp;
    }

    public ControllerCaixaParticula getC() {
        return c;
    }

    public void setC(ControllerCaixaParticula c) {
        this.c = c;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getTxtRes() {
        return txtRes;
    }

    public void setTxtRes(JTextArea txtRes) {
        this.txtRes = txtRes;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParametros = new javax.swing.JPanel();
        lblXp = new javax.swing.JLabel();
        lblK = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        btEnviar = new javax.swing.JButton();
        lblParametros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRes = new javax.swing.JTextArea();
        txtXp = new javax.swing.JTextField();
        lblUnidadeXp = new javax.swing.JLabel();
        lblUnidadeK = new javax.swing.JLabel();
        lblUnidadeA = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtK = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuParametros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAIXA 1D");
        setPreferredSize(new java.awt.Dimension(903, 626));

        panelParametros.setBackground(new java.awt.Color(153, 204, 255));
        panelParametros.setPreferredSize(new java.awt.Dimension(903, 626));

        lblXp.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblXp.setText("Xp:");

        lblK.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblK.setText("k:");

        lblA.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblA.setText("A:");

        btEnviar.setBackground(new java.awt.Color(153, 204, 255));
        btEnviar.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btEnviar.setText("Enviar");
        btEnviar.setToolTipText("");
        btEnviar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        lblParametros.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblParametros.setText("ψ n (x)");

        txtRes.setColumns(20);
        txtRes.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtRes.setRows(5);
        jScrollPane1.setViewportView(txtRes);

        txtXp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXpActionPerformed(evt);
            }
        });

        lblUnidadeXp.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblUnidadeXp.setText("un");

        lblUnidadeK.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblUnidadeK.setText("un");

        lblUnidadeA.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblUnidadeA.setText("un");

        javax.swing.GroupLayout panelParametrosLayout = new javax.swing.GroupLayout(panelParametros);
        panelParametros.setLayout(panelParametrosLayout);
        panelParametrosLayout.setHorizontalGroup(
            panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParametrosLayout.createSequentialGroup()
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelParametrosLayout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblK)
                                    .addComponent(lblA))
                                .addGroup(panelParametrosLayout.createSequentialGroup()
                                    .addComponent(lblXp)
                                    .addGap(3, 3, 3)))
                            .addGap(33, 33, 33)
                            .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtA)
                                .addComponent(txtK)
                                .addComponent(txtXp, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelParametrosLayout.createSequentialGroup()
                                    .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblUnidadeXp)
                                        .addComponent(lblUnidadeK))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblUnidadeA)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelParametrosLayout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelParametrosLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(lblParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        panelParametrosLayout.setVerticalGroup(
            panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParametrosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParametrosLayout.createSequentialGroup()
                        .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelParametrosLayout.createSequentialGroup()
                                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblA)
                                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnidadeA))
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParametrosLayout.createSequentialGroup()
                                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblK))
                                .addGap(24, 24, 24)))
                        .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblXp)
                            .addComponent(txtXp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelParametrosLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUnidadeK)
                            .addComponent(btEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(lblUnidadeXp)))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Menu");

        menuParametros.setBackground(new java.awt.Color(51, 153, 255));
        menuParametros.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        menuParametros.setForeground(new java.awt.Color(255, 255, 255));
        menuParametros.setText("Poço Potencial Unidimensional");
        menuParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuParametrosActionPerformed(evt);
            }
        });
        jMenu1.add(menuParametros);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParametros, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParametros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtXpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXpActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        
        String r = c.pegarParametros();
        txtRes.setText("RESULTADOS\n" + r);
//        txtRes.setText("RESULTADOS\na) Largura da caixa: "  + String.valueOf(r) + "\n" +
//                "b) Nível quântico da partícula: " + "\n" + 
//                "c) Probabilidade de encontrar a partícula na posição Xp: ");
    }//GEN-LAST:event_btEnviarActionPerformed

    private void menuParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuParametrosActionPerformed
        PocoPotencial pp = new PocoPotencial();
        pp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuParametrosActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ParametrosCaixaParticula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ParametrosCaixaParticula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ParametrosCaixaParticula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ParametrosCaixaParticula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ParametrosCaixaParticula().setVisible(true);
//            }
//        });
//    }
    
    public ControllerCaixaParticula c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblK;
    private javax.swing.JLabel lblParametros;
    private javax.swing.JLabel lblUnidadeA;
    private javax.swing.JLabel lblUnidadeK;
    private javax.swing.JLabel lblUnidadeXp;
    private javax.swing.JLabel lblXp;
    private javax.swing.JMenuItem menuParametros;
    private javax.swing.JPanel panelParametros;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtK;
    private javax.swing.JTextArea txtRes;
    private javax.swing.JTextField txtXp;
    // End of variables declaration//GEN-END:variables
}
