/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author unifaljesus
 */
public class Proton extends javax.swing.JFrame {

    /**
     * Creates new form Proton
     */
    public Proton() {
        initComponents();
    }

    public JButton getBtVoltar() {
        return btVoltar;
    }

    public void setBtVoltar(JButton btVoltar) {
        this.btVoltar = btVoltar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getLblA() {
        return lblA;
    }

    public void setLblA(JLabel lblA) {
        this.lblA = lblA;
    }

    public JLabel getLblB() {
        return lblB;
    }

    public void setLblB(JLabel lblB) {
        this.lblB = lblB;
    }

    public JLabel getLblDados() {
        return lblDados;
    }

    public void setLblDados(JLabel lblDados) {
        this.lblDados = lblDados;
    }

    public JLabel getLblLargura() {
        return lblLargura;
    }

    public void setLblLargura(JLabel lblLargura) {
        this.lblLargura = lblLargura;
    }

    public JLabel getLblNf() {
        return lblNf;
    }

    public void setLblNf(JLabel lblNf) {
        this.lblNf = lblNf;
    }

    public JLabel getLblNi() {
        return lblNi;
    }

    public void setLblNi(JLabel lblNi) {
        this.lblNi = lblNi;
    }

    public JLabel getLblUnidade() {
        return lblUnidade;
    }

    public void setLblUnidade(JLabel lblUnidade) {
        this.lblUnidade = lblUnidade;
    }

    public JLabel getLblUnidade1() {
        return lblUnidade1;
    }

    public void setLblUnidade1(JLabel lblUnidade1) {
        this.lblUnidade1 = lblUnidade1;
    }

    public JLabel getLblUnidade2() {
        return lblUnidade2;
    }

    public void setLblUnidade2(JLabel lblUnidade2) {
        this.lblUnidade2 = lblUnidade2;
    }

    public JTextField getTxtAp() {
        return txtAp;
    }

    public void setTxtAp(JTextField txtAp) {
        this.txtAp = txtAp;
    }

    public JTextField getTxtBp() {
        return txtBp;
    }

    public void setTxtBp(JTextField txtBp) {
        this.txtBp = txtBp;
    }

    public JTextField getTxtLargurap() {
        return txtLargurap;
    }

    public void setTxtLargurap(JTextField txtLargurap) {
        this.txtLargurap = txtLargurap;
    }

    public JTextField getTxtNfp() {
        return txtNfp;
    }

    public void setTxtNfp(JTextField txtNfp) {
        this.txtNfp = txtNfp;
    }

    public JTextField getTxtNip() {
        return txtNip;
    }

    public void setTxtNip(JTextField txtNip) {
        this.txtNip = txtNip;
    }

    public JButton getBtEnviar() {
        return btEnviar;
    }

    public void setBtEnviar(JButton btEnviar) {
        this.btEnviar = btEnviar;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLargura = new javax.swing.JLabel();
        lblNi = new javax.swing.JLabel();
        lblNf = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();
        txtLargurap = new javax.swing.JTextField();
        txtNip = new javax.swing.JTextField();
        txtNfp = new javax.swing.JTextField();
        lblDados = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblUnidade1 = new javax.swing.JLabel();
        lblUnidade2 = new javax.swing.JLabel();
        txtAp = new javax.swing.JTextField();
        txtBp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLargura.setText("Largura da caixa (L):");

        lblNi.setText("N inicial da partícula (Ni):");

        lblNf.setText("N final da partícula (Nf):");

        lblUnidade.setText("un");

        txtNfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNfpActionPerformed(evt);
            }
        });

        lblDados.setText("Dados para a probabilidade:");

        lblA.setText("a:");

        lblB.setText("b:");

        lblUnidade1.setText("un");

        lblUnidade2.setText("un");

        jLabel1.setText("Próton");

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNfp, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNip, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLargura)
                        .addGap(34, 34, 34)
                        .addComponent(txtLargurap)
                        .addGap(18, 18, 18)
                        .addComponent(lblUnidade))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDados)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblA)
                                    .addComponent(lblB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAp, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBp, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUnidade1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUnidade2)
                                        .addGap(73, 73, 73)
                                        .addComponent(btVoltar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btEnviar)))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLargura)
                    .addComponent(lblUnidade)
                    .addComponent(txtLargurap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNi)
                    .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNf)
                    .addComponent(txtNfp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblDados)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA)
                    .addComponent(lblUnidade1)
                    .addComponent(txtAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblB)
                    .addComponent(lblUnidade2)
                    .addComponent(txtBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVoltar)
                    .addComponent(btEnviar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNfpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNfpActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        PocoPotencial pp = new PocoPotencial();
        pp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEnviarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Proton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Proton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Proton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Proton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Proton().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblDados;
    private javax.swing.JLabel lblLargura;
    private javax.swing.JLabel lblNf;
    private javax.swing.JLabel lblNi;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JLabel lblUnidade1;
    private javax.swing.JLabel lblUnidade2;
    private javax.swing.JTextField txtAp;
    private javax.swing.JTextField txtBp;
    private javax.swing.JTextField txtLargurap;
    private javax.swing.JTextField txtNfp;
    private javax.swing.JTextField txtNip;
    // End of variables declaration//GEN-END:variables
}
