/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BasicStroke;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Graphics2D;

import javax.swing.Timer;

public class Simulacao extends javax.swing.JFrame {

    private Graphics2D g1, g2, g3, g4, g5;
    private Timer timer;
    private static final int MAX_X = 640;
    private static final int MAX_Y = 65;
    private int amplitude = MAX_Y / 2;
    private int offsetY = MAX_Y / 2;
    private int x = 0;
    private int lastY1= 0, lastY2= 0, lastY3= 0, lastY4= 0, lastY5 = 0;
    private int currentPanelIndex = 0;
    public Simulacao() {
        initComponents();
        g1 = (Graphics2D)n1.getGraphics();
        g2 = (Graphics2D)n2.getGraphics();
        g3 = (Graphics2D)n3.getGraphics();
        g4 = (Graphics2D)n4.getGraphics();
        g5 = (Graphics2D)n5.getGraphics();
        n1.paintComponents(g1);
        n2.paintComponents(g1);
        n3.paintComponents(g1);
        n4.paintComponents(g1);
        n5.paintComponents(g1);
        g1.setStroke(new BasicStroke(3));
        g2.setStroke(new BasicStroke(3));
        g3.setStroke(new BasicStroke(3));
        g4.setStroke(new BasicStroke(3));
        g5.setStroke(new BasicStroke(3));
        timer = new Timer(10, e -> animate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n5 = new javax.swing.JPanel();
        n4 = new javax.swing.JPanel();
        n3 = new javax.swing.JPanel();
        n2 = new javax.swing.JPanel();
        n1 = new javax.swing.JPanel();
        btVoltar = new javax.swing.JButton();
        btIniciar = new javax.swing.JButton();
        btTrocar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 670));
        setMinimumSize(new java.awt.Dimension(800, 670));
        setSize(new java.awt.Dimension(800, 670));
        setType(java.awt.Window.Type.POPUP);

        n5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        javax.swing.GroupLayout n5Layout = new javax.swing.GroupLayout(n5);
        n5.setLayout(n5Layout);
        n5Layout.setHorizontalGroup(
            n5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        n5Layout.setVerticalGroup(
            n5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        n4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        javax.swing.GroupLayout n4Layout = new javax.swing.GroupLayout(n4);
        n4.setLayout(n4Layout);
        n4Layout.setHorizontalGroup(
            n4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        n4Layout.setVerticalGroup(
            n4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        n3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        javax.swing.GroupLayout n3Layout = new javax.swing.GroupLayout(n3);
        n3.setLayout(n3Layout);
        n3Layout.setHorizontalGroup(
            n3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        n3Layout.setVerticalGroup(
            n3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        n2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        javax.swing.GroupLayout n2Layout = new javax.swing.GroupLayout(n2);
        n2.setLayout(n2Layout);
        n2Layout.setHorizontalGroup(
            n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        n2Layout.setVerticalGroup(
            n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        n1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        n1.setOpaque(false);
        n1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout n1Layout = new javax.swing.GroupLayout(n1);
        n1.setLayout(n1Layout);
        n1Layout.setHorizontalGroup(
            n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        n1Layout.setVerticalGroup(
            n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btIniciar.setText("Iniciar");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        btTrocar.setText("Trocar");
        btTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTrocarActionPerformed(evt);
            }
        });

        jLabel1.setText("n = 2");

        jLabel2.setText("n = 1");

        jLabel3.setText("n = 3");

        jLabel4.setText("n = 5");

        jLabel5.setText("n = 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(n5, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addComponent(n4, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addComponent(n3, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addComponent(n2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(btVoltar)
                .addGap(79, 79, 79)
                .addComponent(btIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btTrocar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(n5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(n2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar)
                    .addComponent(btIniciar)
                    .addComponent(btTrocar))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        n1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        PaginaInicial pp = new PaginaInicial();
        pp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
       timer.start();
    }//GEN-LAST:event_btIniciarActionPerformed
    
    private void btTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTrocarActionPerformed
        // Incrementa o índice para alternar entre os gráficos
    currentPanelIndex = (currentPanelIndex + 1) % 5;
    
    // Oculta todos os painéis e limpa os gráficos
    
    // Exibe apenas o painel atual
    
    }//GEN-LAST:event_btTrocarActionPerformed


    private void animate() {
        int panelWidth = MAX_X - 10;
        int panelHeight = MAX_Y;
        if (lastY1 == 0 ||lastY2 == 0|| lastY3== 0|| lastY4== 0|| lastY5== 0){
            lastY1 = (int) (amplitude * Math.sin(0.4 * (panelWidth - 1))) + offsetY;
            lastY2 = (int) (amplitude * Math.sin(0.2 * (panelWidth - 1))) + offsetY;
            lastY3 = (int) (amplitude * Math.sin(0.1 * (panelWidth - 1))) + offsetY;
            lastY4 = (int) (amplitude * Math.sin(0.05 * (panelWidth - 1))) + offsetY;
            lastY5 = (int) (amplitude * Math.sin(0.025 * (panelWidth - 1))) + offsetY;
        }
        // Limpa e redefine a posição x e os pontos de início quando a borda direita é atingida
        if (x >= panelWidth) {
            x = 0;
            
            lastY1 = (int) (amplitude * Math.sin(0.025 * (panelWidth - 1))) + offsetY;
            lastY2 = (int) (amplitude * Math.sin(0.05 * (panelWidth - 1))) + offsetY;
            lastY3 = (int) (amplitude * Math.sin(0.1 * (panelWidth - 1))) + offsetY;
            lastY4 = (int) (amplitude * Math.sin(0.2 * (panelWidth - 1))) + offsetY;
            lastY5 = (int) (amplitude * Math.sin(0.4 * (panelWidth - 1))) + offsetY;
            repaint();

        }
        
        // Calcula os novos valores de y
        int y1 = (int) (amplitude * Math.sin(0.025 * x)) + offsetY;
        int y2 = (int) (amplitude * Math.sin(0.05 * x)) + offsetY;
        int y3 = (int) (amplitude * Math.sin(0.1 * x)) + offsetY;
        int y4 = (int) (amplitude * Math.sin(0.2 * x)) + offsetY;
        int y5 = (int) (amplitude * Math.sin(0.4 * x)) + offsetY;
        
        switch (currentPanelIndex) {
        case 0 -> {
            
            
            g1.setColor(Color.RED);
            g1.drawLine(x - 1, lastY1, x, y1);
            
            
        }
        case 1 -> {
            
            
            g2.setColor(Color.BLUE);
            g2.drawLine(x - 1, lastY2, x, y2);
            
            
        }
        case 2 -> {
            
            
            g3.setColor(Color.GREEN);
            g3.drawLine(x - 1, lastY3, x, y3);
            
            
        }
        case 3 -> {
            
            
            
            g4.setColor(Color.MAGENTA);
            g4.drawLine(x - 1, lastY4, x, y4);
            
            
            
        }
        case 4 -> {
            
            
            g5.setColor(Color.ORANGE);
            g5.drawLine(x - 1, lastY5, x, y5);
            
            
        }
    }
        
        lastY1 = y1;
        lastY2 = y2;
        lastY3 = y3;
        lastY4 = y4;
        lastY5 = y5;
        // Desenha os pontos de forma contínua
        

        x++;
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btTrocar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel n1;
    private javax.swing.JPanel n2;
    private javax.swing.JPanel n3;
    private javax.swing.JPanel n4;
    private javax.swing.JPanel n5;
    // End of variables declaration//GEN-END:variables
}
